package mobilecomputing.hsalbsig.de.mylocation.dao;

import java.util.List;
import mobilecomputing.hsalbsig.de.mylocation.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TRACK".
 */
public class Track {

    private Long id;
    private String Name;
    private java.util.Date LogTime;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient TrackDao myDao;

    private List<Marker> Track;

    public Track() {
    }

    public Track(Long id) {
        this.id = id;
    }

    public Track(Long id, String Name, java.util.Date LogTime) {
        this.id = id;
        this.Name = Name;
        this.LogTime = LogTime;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getTrackDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return Name;
    }

    public void setName(String Name) {
        this.Name = Name;
    }

    public java.util.Date getLogTime() {
        return LogTime;
    }

    public void setLogTime(java.util.Date LogTime) {
        this.LogTime = LogTime;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Marker> getTrack() {
        if (Track == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            MarkerDao targetDao = daoSession.getMarkerDao();
            List<Marker> TrackNew = targetDao._queryTrack_Track(id);
            synchronized (this) {
                if(Track == null) {
                    Track = TrackNew;
                }
            }
        }
        return Track;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetTrack() {
        Track = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
