package mobilecomputing.hsalbsig.de.mylocation.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import mobilecomputing.hsalbsig.de.mylocation.dao.Marker;
import mobilecomputing.hsalbsig.de.mylocation.dao.Track;

import mobilecomputing.hsalbsig.de.mylocation.dao.MarkerDao;
import mobilecomputing.hsalbsig.de.mylocation.dao.TrackDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig markerDaoConfig;
    private final DaoConfig trackDaoConfig;

    private final MarkerDao markerDao;
    private final TrackDao trackDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        markerDaoConfig = daoConfigMap.get(MarkerDao.class).clone();
        markerDaoConfig.initIdentityScope(type);

        trackDaoConfig = daoConfigMap.get(TrackDao.class).clone();
        trackDaoConfig.initIdentityScope(type);

        markerDao = new MarkerDao(markerDaoConfig, this);
        trackDao = new TrackDao(trackDaoConfig, this);

        registerDao(Marker.class, markerDao);
        registerDao(Track.class, trackDao);
    }
    
    public void clear() {
        markerDaoConfig.getIdentityScope().clear();
        trackDaoConfig.getIdentityScope().clear();
    }

    public MarkerDao getMarkerDao() {
        return markerDao;
    }

    public TrackDao getTrackDao() {
        return trackDao;
    }

}
